Swift 4 version
ThinkChaos/reCaptchaiOS pull request #1
Opened 2017-10-11 18:52 UTC by GabrielaBezerra

I updated the code for Swift 4. I hope it's going to be useful to someone, just like the objective-c code was useful to me :)

2018-01-15 16:22 UTC, nnagulavancha-incomm approved these changes

2018-01-16 18:20 UTC, ThinkChaos commented on obj-c/reCaptcha/ViewController.m
> -    wk.opaque = NO;
Please undo this whitespace change

2018-01-16 18:29 UTC, ThinkChaos requested changes

2018-01-16 18:29 UTC, ThinkChaos commented on swift/reCaptcha/script.js
> + (function() {
Please keep move this file up a directory and share it between the projects

2018-01-16 18:29 UTC, ThinkChaos commented on swift/reCaptcha/ViewController.swift
> +    print("Captcha Expired")
Either use a lowercase e in "expired", or revert the change in the Objective-C version

2018-01-16 18:29 UTC, ThinkChaos commented on obj-c/reCaptcha.xcodeproj/project.pbxproj
> +						DevelopmentTeam = 526YR6WHWC;
Please remove your development team info from both projects

2018-01-16 18:30 UTC, ThinkChaos commented
Thanks for the PR!

Sorry I didn't respond earlier, I missed that you had moved the Objective-C version into a directory, and thought you had just removed it.  
I should've at least acknowledged this PR.

Now that I saw that's not the case, I'll happily merge this if you could just change the things I commented on.

2018-10-02 00:23 UTC, closed without merging